name : workflow-github-events-02

on: 
    push:
    pull_request:
    schedule:
        - cron: ' * 5 * * *'  # 
    workflow_dispatch:

jobs:
    github_events_job:
        runs-on: ubuntu-latest
        steps:
            - name: List GitHub event details
              run: |
                echo "GitHub Event Name: ${{ github.event_name }}"
                echo "GitHub Event Path: ${{ github.event_path }}"
                echo "GitHub Event Ref: ${{ github.ref }}"
                echo "GitHub Event Action: ${{ github.event.action || 'N/A' }}"
                echo "Full Event Payload:"
                cat ${{ github.event_path }}    